name: "Continuous Integration"
on: 
  pull_request:
    branches: '*'

permissions:
  contents: read
  packages: write

jobs:
  test:    
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install dependencies
        run: yarn install
      - name: Lint code
        run: yarn lint
      - name: Run Tests
        run: yarn test
